  trigger:
    branches:
      include:
        - main  
  pool:
    name: 'Default'

  steps:
  #Download artifact from build pipeline
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifact'
    inputs:
      artifact: 'drop'
      path: '$(Pipeline.Workspace)'
      buildType: 'current'
  
  # Check the artifact directory structure for debugging
  - script: |
      echo "Listing downloaded artifacts..."
      dir $(Pipeline.Workspace)/drop
    displayName: 'List Downloaded Artifact Files'
  
  #Deploy to Azure Function app
  - task: AzureFunctionApp@1
    displayName: 'Deploy Azure Function App'
    inputs:
      azureSubscription: 'alice'
      appName: 'funcappdevoir2'
      package: '$(Pipeline.Workspace)/drop/**/*.zip'
      appType: 'functionApp'


