trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DeleteFiles@1
    displayName: 'Clean up obj and bin folders'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**/bin/**;**/obj/**'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: "Build Function App"
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      configuration: 'Release'
      arguments: '/p:OutputPath=$(Build.ArtifactStagingDirectory)/output'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Function App'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      configuration: 'Release'
      publishWebProjects: false
      zipAfterPublish: true
      arguments: '--output $(Build.ArtifactStagingDirectory)/output'

  - task: ArchiveFiles@2
    displayName: 'Zip Artifact'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/output'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/output.zip'
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/output
    displayName: 'Publish Artifact'
    artifact: 'drop'
    
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifact'
    inputs:
      artifact: 'drop'
      path: '$(Pipeline.Workspace'
      buildType: 'current'
  - task: AzureFunctionApp@1
    displayName: 'Deploy to Azure Function App'
    inputs:
      azureSubscription: 'alice'
      appName: 'funcappdevoir2'
      package: '$(Pipeline.Workspace)/drop/output.zip'
      appType: 'functionApp'


