# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main


pool:
  name: 'Default'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'
    
  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages'
    inputs:
      restoreSolution: '**/*.sln'
  
  - task: DotNetCoreCLI@2
    displayName: "Build Function App"
    inputs:
      command: 'build'
      projects: '**/*.sln'
      configuration: 'Release'
  
  - task: DotNetCoreCLI@2
    displayName: 'Publish Function App'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      configuration: 'Release'
      zipAfterPublish: true
      publishWebProjects: false
  
  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)
    displayName: 'Publish Artifact'
    artifact: 'drop'

